name: Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - run: bun install --frozen-lockfile
      - run: bun test --coverage
          
